stages:
  preprocess:
    cmd: python ${preprocess.script}
    params:
      - preprocess
    deps:
      - ${preprocess.script}
      - ${preprocess.input_train}
      - ${preprocess.input_val}
      - ${preprocess.input_test}
    outs:
      - ${preprocess.output_train}
      - ${preprocess.output_val}
      - ${preprocess.output_test}
  featurize:
    cmd: python ${featurize.script}
    params:
      - preprocess
      - featurize
    deps:
      - ${featurize.script}
      - ${preprocess.output_train}
      - ${preprocess.output_val}
      - ${preprocess.output_test}
    outs:
      - ${featurize.output_train}
      - ${featurize.output_val}
      - ${featurize.output_test}
      - ${featurize.mlb_out}:
          cache: true
      - ${featurize.tfidf_vectorizer_out}:
          cache: true
  train:
    cmd: python ${train.script}
    params:
      - featurize
      - train
    deps:
      - ${train.script}
      - ${featurize.output_train}
    outs:
      - ${train.model_out}:
          cache: true
  evaluate:
    cmd: python ${evaluate.script}
    params:
      - featurize
      - train
      - evaluate
    deps:
      - ${evaluate.script}
      - ${train.model_out}
      - ${featurize.output_val}
      # - ${featurize.output_test}
    # outs:
    #   - ${evaluate.prc_img}
    #   - ${evaluate.roc_img}
    metrics:
      - ${evaluate.scores_path}:
          cache: false
    # plots:
    #   - ${evaluate.prc_json}:
    #       cache: false
    #   - ${evaluate.roc_json}:
    #       cache: false
