stages:
    preprocess:
        cmd: python src/1_preprocessing.py
        deps:
            - src/1_preprocessing.py
        outs:
            - output/preprocessed_data.joblib
    createBag:
        cmd: python src/2_bag_of_words.py
        deps:
            - src/2_bag_of_words.py
            - output/preprocessed_data.joblib
        outs:
            - output/bag_of_words.joblib
            - output/words_dictionaries.joblib
    train:
        cmd: python src/3_train.py
        deps:
            - src/3_train.py
            - output/bag_of_words.joblib
        outs:
            - output/multi_label_binarizer.joblib
            - output/classifier.joblib
            - output/val_data.joblib
    predict:
        cmd: python src/4_predict.py
        deps:
            - src/4_predict.py
            - output/bag_of_words.joblib
            - output/classifier.joblib
        outs:
            - output/prediction_results.joblib
    evaluation:
        cmd: python src/5_evaluation.py
        deps:
            - src/5_evaluation.py
            - output/prediction_results.joblib

        metrics:
            - results/metrics.json:
                  cache: false
    analyze:
        cmd: python src/6_analyze_features.py
        deps:
            - src/6_analyze_features.py
            - output/multi_label_binarizer.joblib
            - output/words_dictionaries.joblib
            - output/classifier.joblib
