feature {
  name: "SQLite/PHP read-only?"
  type: BYTES
  domain: "SQLite/PHP read-only?"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
string_domain {
  name: "SQLite/PHP read-only?"
  value: "\"gem install rails\" fails with DNS error"
  value: "Adjusting camera for visible Three.js shape"
  value: "Align radio buttons horizontally in django forms"
  value: "Altering HTTP Responses in Firefox Extension"
  value: "Alternatives to Java\'s Scanner class for console input"
  value: "Apache spark and python lambda"
  value: "Assigning a lambda to an Action<T>"
  value: "Best Practice For List of Polymorphic Objects in C++"
  value: "Calculate Throughput"
  value: "Calendar display using Java Swing"
  value: "Coin toss with JavaScript and HTML"
  value: "Compile C code for Windows 64"
  value: "Count Number of Rows in a SQLite Database"
  value: "Creating Multiple textboxes dynamically"
  value: "Creating an Interactive bar Chart out of Google Analytics Data"
  value: "Disadvantage of object composition over class inheritance"
  value: "Ensuring Thread-Safety On Static Methods In C#"
  value: "Error while deploying to Tomcat: tomcatManager status code:404, ReasonPhrase:Not Found"
  value: "Extend Request class in Laravel 5"
  value: "Facebook Connect from Localhost, doing some weird stuff"
  value: "Frustrating UIWebView Delegate Crash issue"
  value: "Google Maps API v3: Looping through and adding polylines to a map"
  value: "Having trouble setting headers in a QNetworkRequest, can\'t understand why"
  value: "How I can fill my DropDownList with Data from a XML File in my ASP.NET Application"
  value: "How do I format a double to a string and only show decimal digits when necessary?"
  value: "How do I start a session in a Python web application?"
  value: "How to Avoid \"Used by another process\" When using File.Copy in C#"
  value: "How to change view-state value dynamically?"
  value: "How to get the value of a method argument via reflection in Java?"
  value: "How to open and close a website using default browser with python"
  value: "How to properly manage Tomcat web apps inside Eclipse?"
  value: "How to set Blank excel cell using POI"
  value: "How to show SQL queries run in the Rails console?"
  value: "How to use Qt Creator with Visual C++ compiler on windows?"
  value: "I want to compare the (dt.Rows[1].ItemArray[1].ToString()) with 1,2,3,4 : but does not Work?? show me error"
  value: "In python, how to convert a hex ascii string to raw internal binary string?"
  value: "Install ClickOnce without running"
  value: "Installing eventmachine on windows 8"
  value: "Javascript: how to get values from all selected checkboxes from a table"
  value: "Join two un-related tables using JPA EntityManager"
  value: "Knockout maping.fromJS for observableArray from json object. Data gets lost"
  value: "LD_LIBRARY_PATH ignored on Android sometimes"
  value: "Laravel Response::download() to show images in Laravel"
  value: "Load factor and capacity of Hash Table"
  value: "Magento multi language rewrites SEO fix?"
  value: "Mocking Reflection based calls"
  value: "Most efficient way to concatenate strings?"
  value: "Open all external links open in a new tab apart from a domain"
  value: "PHP calling a class method with class name as variable string"
  value: "PHP not displaying errors"
  value: "PHP remove characters after last occurrence of a character in a string"
  value: "PHP security: \'Nonce\' or \'unique form key\' problem"
  value: "PHP: Is there any Bluetooth RFCOMM library?"
  value: "Pretty Print Distances for iOS"
  value: "Programmatically trigger a jQuery-UI draggable\'s \"drag\" event"
  value: "PyDev-Eclipse Python not configured"
  value: "Python Pandas : How to skip columns when reading a file?"
  value: "Python imaging library show() on Windows"
  value: "Python socket server receive image"
  value: "Random Number between 2 variables/values"
  value: "Reading an Excel file with C# causes OleDbException to be thrown"
  value: "Registry.GetValue always return null"
  value: "Removing sheet from Excel 2005 using PHP"
  value: "Round off in JAVA"
  value: "Save PHP date string into MySQL database as timestamp"
  value: "Split string into a list, but keeping the split pattern"
  value: "Spring Batch: SimpleJobRepository - Example not working"
  value: "SyntaxError: Unexpected token"
  value: "Unable to get property \'1\' of undefined or null reference"
  value: "Unbalanced parenthesis error with Regex"
  value: "Using a USB printer with C#, with and without driver or API"
  value: "Vaadin multiple browser windows/tabs"
  value: "Vector iterator not dereferencable in for loop"
  value: "Want to seperate the integer part and fractional part of float number in python"
  value: "What is an Event Handle?"
  value: "What is the difference between matrix() and as.matrix() in r?"
  value: "What is the most effective way for float and double comparison?"
  value: "What is wrong with this Rspec test"
  value: "Why PHP session is deleted on page reload?"
  value: "Why am I getting OleDBException \"No value given for one or more required parameters?\""
  value: "Why is listShuttle component in richFaces not getting updated?"
  value: "Wordpress - wp_rewrite rules"
  value: "XCode - Code Coverage?"
  value: "Yii Condition with multiple AND/ORs - Operator Precedence"
  value: "com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect"
  value: "error: expected unqualified-id before \342\200\230const\342\200\231 on line 8"
  value: "fullcalendar prev / next click"
  value: "how to check whether two matrixes are identical in OpenCV"
  value: "jQuery - selected option value contains string"
  value: "java.lang.NullPointerException when trying to read files"
  value: "java.nio.charset.MalformedInputException: Input length = 1"
  value: "loop focus of input fields inside a form"
  value: "math.h compilation error: expected declaration specifiers or \'...\' before \'(\'"
  value: "mySQL Search Statement with Multiple filters"
  value: "php Fatal error: Function name must be a string in"
  value: "python selenium import my regular firefox profile ( add-ons)"
  value: "showing alert box using php and javascript"
  value: "that, self or me \342\200\224 which one to prefer in JavaScript?"
  value: "ul in the form not sending to the $_POST"
}
