{
 "title": "overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scraping timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "scrape_timestamp", "legendFormat": "Last given out timestamp" }
   ]
  },
  {
   "title": "API key quota's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "api_key_0_quota", "legendFormat": "Key 0" },
    { "expr": "api_key_1_quota", "legendFormat": "Key 1" }
   ]
  },
  {
   "title": "Scraping overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(num_questions_retrieved_total[$__rate_interval])",
     "legendFormat": "Rate of Number of posts scraped"
    },
    {
     "expr": "rate(scrape_count[$__rate_interval])",
     "legendFormat": "Rate of Number of requests to StackExchange API"
    },
    {
     "expr": "rate(get_timerange_duration_count[$__rate_interval])",
     "legendFormat": "Number of timeranges given out by controller"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(train_duration_sum[$__rate_interval]) / rate(train_duration_count[$__rate_interval]"
    },
    {
     "expr": "rate(train_duration_sum[$__rate_interval])"
    },
    {
     "expr": "rate(train_duration_count[$__rate_interval]"
    }
   ]
  }
 ]
}