name: Lint using mllint

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

env:
  RESULTS_FILE: results.md

jobs:
  lint-ml:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install mllint[tools]
        
    - name: Lint using mllint
      run: |
        mllint . -o ${{ env.RESULTS_FILE }}

    - name: Comment results to PR
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: ${{ env.RESULTS_FILE }}
