name: Test
on:
    pull_request:
    push: { branches: main }

jobs:
    test:
        name: Run test suite
        runs-on: ubuntu-20.04
        container:
            image: ghcr.io/${{ github.repository }}
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Check packages
              run: pip3 list

            - name: Install pytest
              run: pip3 install pytest

            - name: Data validation
              run: pytest static_analysis/data_validation.py

            - name: Run tests
              run: |
                  pytest tests/preprocessing.py 
                  pytest tests/bag_of_words.py
                  pytest tests/tfidf.py
                  pytest tests/models.py

            - name: Check quality of the code
              run: pylint src
